Fix building examples
"helloUnicode.d(17): Deprecation: module std.c.locale is deprecated
- Import core.stdc.locale instead"

"printw.d(27): Error: function expected before (), not module printw
of type void"